### PR TITLE
cargo-insta: allow passing --profile

### LINKED ISSUE #381: Allow passing `--profile`
I know adding the standard cargo options has been a long tail. One that insta doesn't currently support is `--profile`:

These both fail:
```sh
cargo insta test --profile=dev
cargo insta test -- --profile=dev
```

(Probably it's too late now; would there be an option to forward options to cargo rather than trying to handle them as first-class options in insta? Possibly after a `--`, like `cargo insta test -- --profile=dev -- test_name`??)

### PR DESCRIPTION
**Pull request by tamird**
Closes #381.

### CODE REVIEW

**Review by mitsuhiko — APPROVED** [review]

**Comment by tamird** [comment]
Thanks @mitsuhiko. Could you cut a new cargo-insta release with this fix please?

File: cargo-insta/src/cli.rs [hunk 1]
```diff
@@ -151,6 +151,9 @@ pub struct TestCommand {
     /// Build artifacts in release mode, with optimizations
     #[structopt(long)]
     pub release: bool,
+    /// Build artifacts with the specified profile
+    #[structopt(long)]
+    pub profile: String,
```
Comment (marcospb19) [inline cargo-insta/src/cli.rs:156]: Now profiles are required, the following doesn't work anymore:

```sh
cargo insta test
```

You need this:

```sh
cargo insta test --profile dev -- ui
```

Was this intended? If not I can create the fix PR with

```diff
-pub profile: String,
+pub profile: Option<String>,
```

Comment (tamird) [reply cargo-insta/src/cli.rs:156]: Oh boy, it's worse than that. The logic is looking at `features` rather than `profile`. Feel free to send a fix for both issues, else I'll do so tomorrow.

Comment (marcospb19) [reply cargo-insta/src/cli.rs:156]: I'll let you go for it because I didn't detect the other issue you just did :V

Comment (tamird) [reply cargo-insta/src/cli.rs:156]: https://github.com/mitsuhiko/insta/pull/407
