### PR TITLE
Fix glob! input_file on Windows

### LINKED ISSUE #336: `glob!` on Windows doesn't seem to include `input_file`
### What happened?

Thanks for the recent changes in 1.26! I've updated PRQL with the latest changes, they're great.

The last thing I'm having trouble with is forcing updates — Windows seems to produce different metadata, which causes its tests to fail. Specifically, Windows doesn't seem to show `input_file` in `glob!` tests. Even if we skipped those tests, anyone contributing on Windows would be submitting PRs with huge diffs.

I looked around the insta code, but couldn't find why that might happen (looks like there isn't much platform-specific code in `insta`, so it's a puzzle, and unfortunately I don't have a Windows machine, so it's difficult to debug). 

Here's an example: https://github.com/PRQL/prql/actions/runs/3861652619/jobs/6582754606#step:3:2726. (Note I made the tests pass there to see the diff, but otherwise it fails; e.g. [here](https://github.com/PRQL/prql/actions/runs/3861420435/jobs/6582387689))

Any thoughts on why that might be happening? If not I can look more.

### Reproduction steps

_No response_

### Insta Version

1.26

### rustc Version

rustc 1.65.0 (897e37553 2022-11-02)

### What did you expect?

_No response_

### PR DESCRIPTION
**Pull request by smonicas**
Fix #336 
The issue is caused due to not canonicalize the stripped prefix when localizing the path.
For example in my environment i get `"D:\\Rust\\insta"` to strip from `"\\\\?\\D:\\Rust\\insta\\tests\\inputs\\goodbye.txt"` while when canonicalized becomes the correct prefix `"\\\\?\\D:\\Rust\\insta"`.
I used unwrap with the assumption that if canonicalize fails the previous call to canonicalize would also fail and it doesn't arrive at the unwrap.

### CODE REVIEW

File: src/runtime.rs [hunk 1]
```diff
@@ -315,7 +315,7 @@ impl<'a> SnapshotAssertionContext<'a> {
             .canonicalize()
             .ok()
             .and_then(|s| {
-                s.strip_prefix(self.cargo_workspace.as_path())
+                s.strip_prefix(self.cargo_workspace.canonicalize().unwrap())
```
Comment (mitsuhiko) [inline src/runtime.rs:318]: Unfortunately `canonicalize` can fail quite commonly. Ideally the error here is swallowed.

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
